version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      POSTGRES_DB: SalesScoutDb
      POSTGRES_USER: user_an
      POSTGRES_PASSWORD: w8rujf544
    volumes:
      - ./daten:/var/lib/postgresql/data
    ports:
      - "5432:5432"


